#!/bin/bash

if [ -z $1 ]; then
	echo You need to provides the first argument to be the folder where you want to store all repos.
	exit
fi

source vars

COUNT=1

cd $1

for i in `curl $urlbase/listrepos.php`; do

	if [ $COUNT = 1 ]; then
		if [ $i = "error" ]; then
			echo Error. Bye.
			exit
		fi
	else
		echo $i

		echo ""
		echo -- Downloading $i

		if [ -d $i ]; then
			cd $i
			git pull origin master
			cd ..
		else
			git clone git@github.com:$username/$i
		fi

		echo $i finished
		echo $COUNT repositories processed.
	fi

	COUNT=$(($COUNT+1))

done
